import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#282c34",
  },
  eventName: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "bold",
    marginLeft: 20,
  },
  input: {
    backgroundColor: "#167ac6",
    height: 50,
    borderRadius: 4,
    color: "#FDFCFE",
    padding: 20,
    fontSize: 18,
    flex: 1,
    marginLeft: 20,
    marginTop: 20,
    width: "100%",
  },
  buttonText: {
    color: "#fff",
    fontSize: 40,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  Button: {
    width: 40,
    height: 50,
    borderRadius: 5,
    backgroundColor: "#167ac6",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 20,
    marginLeft: 2,
    marginTop: 20,
  },
  form: {
    width: "100%",
    flexDirection: "row",
    alignContent: "center",
  },
  listEmpy: {
    fontSize: 16,
    color: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 30,
    marginTop: 10,
  },
  date: {
    color: "#fff",
    fontSize: 15,
    borderRadius: 50,
    marginLeft: 20,
  },
  nameEvent: {
    color: "#fff",
    fontSize: 20,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    marginTop: 15,
  },
});
